"""initial schema: users, members, coaches, cards, classes, bookings, attendances

Revision ID: 7767fac4ee01
Revises: 
Create Date: 2026-06-24 18:19:55.356008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7767fac4ee01'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('total_visits', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('coaches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('gender', sa.Enum('male', 'female', 'other', name='gender', native_enum=False, length=8), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('specialty', sa.String(length=255), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('hired_at', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('coaches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coaches_name'), ['name'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'staff', 'member', name='userrole', native_enum=False, length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('class_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('coach_id', sa.Integer(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['coach_id'], ['coaches.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('class_definitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_class_definitions_name'), ['name'], unique=False)

    op.create_table('member_profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('real_name', sa.String(length=64), nullable=False),
    sa.Column('gender', sa.Enum('male', 'female', 'other', name='gender', native_enum=False, length=8), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('id_card_encrypted', sa.String(length=255), nullable=True),
    sa.Column('emergency_contact', sa.String(length=64), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('id_card_encrypted')
    )
    with op.batch_alter_table('member_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_member_profiles_phone'), ['phone'], unique=True)

    op.create_table('membership_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_no', sa.String(length=32), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('card_type_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('remaining_visits', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('active', 'frozen', 'expired', 'cancelled', name='cardstatus', native_enum=False, length=16), nullable=False),
    sa.Column('issued_by', sa.Integer(), nullable=True),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.Column('frozen_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['card_type_id'], ['card_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['issued_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['member_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('membership_cards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_membership_cards_card_no'), ['card_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_membership_cards_member_id'), ['member_id'], unique=False)

    op.create_table('class_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_def_id', sa.Integer(), nullable=False),
    sa.Column('coach_id', sa.Integer(), nullable=True),
    sa.Column('start_at', sa.DateTime(), nullable=False),
    sa.Column('end_at', sa.DateTime(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('scheduled', 'cancelled', 'finished', name='sessionstatus', native_enum=False, length=16), nullable=False),
    sa.ForeignKeyConstraint(['class_def_id'], ['class_definitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['coach_id'], ['coaches.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('class_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_class_sessions_class_def_id'), ['class_def_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_class_sessions_start_at'), ['start_at'], unique=False)

    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('booked', 'cancelled', 'attended', 'no_show', name='bookingstatus', native_enum=False, length=16), nullable=False),
    sa.Column('booked_at', sa.DateTime(), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('source', sa.Enum('self', 'admin', name='bookingsource', native_enum=False, length=8), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['membership_cards.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['member_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['class_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bookings_member_id'), ['member_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_session_id'), ['session_id'], unique=False)
        batch_op.create_index('uq_bookings_member_session_active', ['member_id', 'session_id'], unique=True, sqlite_where=sa.text("status != 'cancelled'"))

    op.create_table('attendances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('checked_in_at', sa.DateTime(), nullable=False),
    sa.Column('checked_in_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['checked_in_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attendances')
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_index('uq_bookings_member_session_active', sqlite_where=sa.text("status != 'cancelled'"))
        batch_op.drop_index(batch_op.f('ix_bookings_session_id'))
        batch_op.drop_index(batch_op.f('ix_bookings_member_id'))

    op.drop_table('bookings')
    with op.batch_alter_table('class_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_class_sessions_start_at'))
        batch_op.drop_index(batch_op.f('ix_class_sessions_class_def_id'))

    op.drop_table('class_sessions')
    with op.batch_alter_table('membership_cards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_membership_cards_member_id'))
        batch_op.drop_index(batch_op.f('ix_membership_cards_card_no'))

    op.drop_table('membership_cards')
    with op.batch_alter_table('member_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_member_profiles_phone'))

    op.drop_table('member_profiles')
    with op.batch_alter_table('class_definitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_class_definitions_name'))

    op.drop_table('class_definitions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    with op.batch_alter_table('coaches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coaches_name'))

    op.drop_table('coaches')
    op.drop_table('card_types')
    # ### end Alembic commands ###
